data<-read.table("household_power_consumption.txt",sep=";",header=TRUE, colClasses=c("factor","factor","real","real","real","real","real","real","real"),na.strings="?")
data2<-subset(data, (data$Date == "1/2/2007") | (data$Date == "2/2/2007"))
dateTime  <- as.POSIXlt(paste(as.Date(data2$Date,format="%d/%m/%Y"), data2$Time, sep=" "))
with(data2, plot(dateTime,data2$Sub_metering_1,type="l",ylab="Energy sub metering", xlab="",col="black"))
with(data2, lines(dateTime,data2$Sub_metering_2,type="l",ylab="Energy sub metering", xlab="", col = "red"))
with(data2, lines(dateTime,data2$Sub_metering_3,type="l",ylab="Energy sub metering", xlab="", col = "blue"))
legend("topright", pch = "-", col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),cex=0.5)
dev.copy(png,file="plot3.png")
dev.off()